title: Yiqing's Homepage
description: "Personal page"
author:
  name: "Yiqing Zhao"
  email: "yiqingzhao94@gmail.com"
  url: "https://zyq823.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "yiqingzhao94"
year : "2020"
